coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false
        comment:

comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
