coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        informational: false  # Set to false to enforce CI failure if below target
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - tests/
  - __pycache__/
  - node_modules/
  - .pytest_cache/
  - .github/