coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default